### ISSUE TITLE
[cms] Investigate undefined case in populateSearch ingest

### ISSUE THREAD

**Issue by jhmullen** [Datawheel/canon#1133]
```
1|oec-site  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|oec-site  | TypeError: Url must be a string. Received undefined
1|oec-site  |     at normalize (/home/deploy/oec-website/node_modules/url-join/lib/url-join.js:12:13)
1|oec-site  |     at /home/deploy/oec-website/node_modules/url-join/lib/url-join.js:75:12
1|oec-site  |     at MondrianDataSource.fetchCube (/home/deploy/oec-website/node_modules/@datawheel/olap-client/dist/index.cjs.js:1372:19)
1|oec-site  |     at Client.getCube (/home/deploy/oec-website/node_modules/@datawheel/olap-client/dist/index.cjs.js:2157:24)
1|oec-site  |     at populateSearch (/home/deploy/oec-website/node_modules/@datawheel/canon-cms/src/utils/populateSearch.js:102:29)
1|oec-site  |     at /home/deploy/oec-website/node_modules/@datawheel/canon-cms/src/api/cmsRoute.js:410:11
```

**Comment by jhmullen** [comment]
Francisco indicated to me this occurs when cubeName is undefined:

https://github.com/Datawheel/canon/blob/master/packages/cms/src/utils/populateSearch.js#L103

Original convo is here: https://datawheel.slack.com/archives/CMDDH18NP/p1605538022006200

Work out whether there's a case that `cubeName` could be null when running a reingest

**Comment by jhmullen** [comment]
This was due to a transient error with the cube being down. Closing this as better error reporting is a goal of #1277
